#!/bin/sh
# lm - CMake shortcut command (Intended for addictgamer)

mkdir -p build/debug

cd build/debug

# If CMake cannot find one of these, uncomment and write the correct path
#export GLEW_ROOT="E:/Projects/C++/Libs/glew-1.7.0"
#export GLM_ROOT="E:/Projects/C++/Libs/glm-0.9.3.4"

# SFML
#export SFML_ROOT="E:/Projects/C++/Libs/SFML-2.0-rc-gcc"

# Change this to Unix Makefiles on Linux
cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" ../..

#make -j8
make

cd ../..

rm include -r
mkdir include
mkdir include/GEngine
cp src/* -r include/GEngine

mkdir bin
cp build/debug/libgengine.a bin/libgengine.a
