#!/bin/sh
# cm - CMake shortcut command

SOURCE_DIR=$(printf "%q" "$PWD") # escapes the dir with backslashes

rm -rf include bin/libgengine.a

mkdir -p build/debug

cd build/debug

# If CMake cannot find one of these, uncomment and write the correct path
#export GLEW_ROOT="E:/Projects/C++/Libs/glew-1.7.0"
#export GLM_ROOT="E:/Projects/C++/Libs/glm-0.9.3.4"

# SFML
#export SFML_ROOT="E:/Projects/C++/Libs/SFML-2.0-rc-gcc"

# Change this to Unix Makefiles on Linux
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SOURCE_DIR -G "Unix Makefiles" ../..

#make -j8
make install

